### ISSUE TITLE
Quilt gets mismatched for Fabric

### ISSUE THREAD

**Issue by Rafii2198** [natanfudge/Crashy#50] opened 2022-08-15 21:07 UTC
I wanted to use [this crash report](https://crashy.net/ssYUjAxfS52B3HgTB6Cj) and noticed it shows that I used Fabric, while it should show Quilt instead.

**Comment by natanfudge** [comment] 2023-05-19 16:01
Duplicate of #74

**Closed by natanfudge** 2023-05-19 16:01 UTC
