### ISSUE TITLE
[Suggestion] add mods list table for Quilt

### ISSUE THREAD

**Issue by cootshk** [natanfudge/Crashy#76] opened 2023-03-19 14:56 UTC
# example table:

|Index|Mod|ID|Version|
|---:|---|---|:---:|
| | | | |
|    15 | CIT Resewn                                        | citresewn                                             | 1.1.3+1.19.3                 |
|    13 | CIT Resewn: Defaults                              | citresewn-defaults                                    | 1.1.3+1.19.3                 |
|    82 | Capes                                             | capes                                                 | 1.5.1+1.19.3                 |
|    55 | Fabric Language Kotlin                            | fabric-language-kotlin                                | 1.9.0+kotlin.1.8.0           |
|    18 | Indium                                            | indium                                                | 1.0.12+mc1.19.3              |
|    33 | Iris                                              | iris                                                  | 1.5.1                        |
|    25 | Java HotSpot(TM) 64-Bit Server VM                 | java                                                  | 17                           |
|    57 | LibZoomer                                         | libzoomer                                             | 0.5.1+1.19.3                 |
|    75 | Lithium                                           | lithium                                               | 0.10.4                       |
|    95 | Minecraft                                         | minecraft                                             | 1.19.3                       |
|     1 | MixinExtras                                       | com_github_llamalad7_mixinextras                      | 0.1.1                        |
|    44 | Mod Menu                                          | modmenu                                               | 5.0.2                        |
|    41 | Ok Zoomer                                         | ok_zoomer                                             | 5.0.0-beta.10+1.19.3         |
|    16 | OmegaConfig                                       | omega-config                                          | 1.2.3-1.18.1                 |
|     4 | Phosphor                                          | phosphor                                              | 0.8.1                        |
|   111 | Quilt Advancement API                             | quilt_advancement                                     | 4.0.0-beta.5+1.19.3          |
|    51 | Quilt Base API                                    | quilt_base                                            | 4.0.0-beta.5+1.19.3          |
|    67 | Quilt Biome API                                   | quilt_biome                                           | 4.0.0-beta.5+1.19.3          |
|   109 | Quilt Block Content Registry API                  | quilt_block_content_registry                          | 4.0.0-beta.5+1.19.3          |
|    45 | Quilt Block Entity API                            | quilt_block_entity                                    | 4.0.0-beta.5+1.19.3          |
|    30 | Quilt Block Extensions API                        | quilt_block_extensions                                | 4.0.0-beta.5+1.19.3          |
|    66 | Quilt Client Command API                          | quilt_client_command                                  | 4.0.0-beta.5+1.19.3          |
|    29 | Quilt Command API                                 | quilt_command                                         | 4.0.0-beta.5+1.19.3          |
|    64 | Quilt Crash Info                                  | quilt_crash_info                                      | 4.0.0-beta.5+1.19.3          |
|    38 | Quilt Dimension API                               | quilt_dimension                                       | 4.0.0-beta.5+1.19.3          |
|    52 | Quilt Entity API                                  | quilt_entity                                          | 4.0.0-beta.5+1.19.3          |
|    96 | Quilt Entity Events                               | quilt_entity_events                                   | 4.0.0-beta.5+1.19.3          |
|    40 | Quilt Entity Networking API                       | quilt_entity_networking                               | 4.0.0-beta.5+1.19.3          |
|    22 | Quilt Item Content Registry API                   | quilt_item_content_registry                           | 4.0.0-beta.5+1.19.3          |
|    56 | Quilt Item Extension API                          | quilt_item_extension                                  | 4.0.0-beta.5+1.19.3          |
|    20 | Quilt Item Setting API                            | quilt_item_setting                                    | 4.0.0-beta.5+1.19.3          |
|    98 | Quilt Lifecycle Events                            | quilt_lifecycle_events                                | 4.0.0-beta.5+1.19.3          |
|    68 | Quilt Loader                                      | quilt_loader                                          | 0.17.8                       |
|    27 | Quilt Multipart Entity API                        | quilt_entity_multipart                                | 4.0.0-beta.5+1.19.3          |
|    83 | Quilt Networking                                  | quilt_networking                                      | 4.0.0-beta.5+1.19.3          |
|    53 | Quilt Points of Interest                          | quilt_points_of_interest                              | 4.0.0-beta.5+1.19.3          |
|    88 | Quilt Recipe API                                  | quilt_recipe                                          | 4.0.0-beta.5+1.19.3          |
|    74 | Quilt Registry API                                | quilt_registry                                        | 4.0.0-beta.5+1.19.3          |
|    63 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment                       | 4.0.0-beta.5+1.19.3          |
|    79 | Quilt Resource Loader                             | quilt_resource_loader                                 | 4.0.0-beta.5+1.19.3          |
|    76 | Quilt Screen API                                  | quilt_screen                                          | 4.0.0-beta.5+1.19.3          |
|   100 | Quilt Status Effect API                           | quilt_status_effect                                   | 4.0.0-beta.5+1.19.3          |
|    92 | Quilt Surface Rule API                            | quilt_surface_rule                                    | 4.0.0-beta.5+1.19.3          |
|    78 | Quilt Tags API                                    | quilt_tags                                            | 4.0.0-beta.5+1.19.3          |
|    93 | Quilt Tooltip API                                 | quilt_tooltip                                         | 4.0.0-beta.5+1.19.3          |
|    43 | Quilt Vehicle API                                 | quilt_vehicle                                         | 4.0.0-beta.5+1.19.3          |
|    46 | Quilt Villager API                                | quilt_villager                                        | 4.0.0-beta.5+1.19.3          |
|    84 | Quilted Fabric API                                | quilted_fabric_api                                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    62 | Quilted Fabric API Base                           | quilted_fabric_api_base                               | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    70 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    59 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   101 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   110 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   108 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    37 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    39 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    36 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    48 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   105 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    50 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    28 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    65 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    85 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    49 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    91 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    61 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    31 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    54 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    23 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   112 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    97 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    69 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    90 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    21 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    60 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   107 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    58 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                              | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    32 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    26 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    47 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   106 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   102 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    94 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    71 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    24 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    34 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    77 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    80 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    42 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    73 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    35 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1             | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    99 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   103 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    86 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    87 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    81 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    72 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    89 | Sodium                                            | sodium                                                | 0.4.8+build.22               |
|   104 | SpruceUI                                          | spruceui                                              | 4.1.0+1.19.3                 |
|     9 | antlr4-runtime                                    | org_antlr_antlr4-runtime                              | 4.11.1                       |
|     7 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.5                       |
|    17 | glsl-transformer                                  | io_github_douira_glsl-transformer                     | 2.0.0-pre8                   |
|    12 | jcpp                                              | org_anarres_jcpp                                      | 1.4.14                       |
|     8 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                   | 1.8.0                        |
|     2 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                    | 1.8.0                        |
|     3 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.8.0                        |
|     5 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.8.0                        |
|    14 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
|     6 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
|    10 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
|    19 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
|    11 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
|     0 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |

# what it looks like in the crash report:
[pastebin](https://pastebin.com/Qk2S0afV) (too long for github)
# what it should format to (raw table data):
```
|Index|Mod|ID|Version|
|---:|---|---|:---:|
| | | | |
|    15 | CIT Resewn                                        | citresewn                                             | 1.1.3+1.19.3                 |
|    13 | CIT Resewn: Defaults                              | citresewn-defaults                                    | 1.1.3+1.19.3                 |
|    82 | Capes                                             | capes                                                 | 1.5.1+1.19.3                 |
|    55 | Fabric Language Kotlin                            | fabric-language-kotlin                                | 1.9.0+kotlin.1.8.0           |
|    18 | Indium                                            | indium                                                | 1.0.12+mc1.19.3              |
|    33 | Iris                                              | iris                                                  | 1.5.1                        |
|    25 | Java HotSpot(TM) 64-Bit Server VM                 | java                                                  | 17                           |
|    57 | LibZoomer                                         | libzoomer                                             | 0.5.1+1.19.3                 |
|    75 | Lithium                                           | lithium                                               | 0.10.4                       |
|    95 | Minecraft                                         | minecraft                                             | 1.19.3                       |
|     1 | MixinExtras                                       | com_github_llamalad7_mixinextras                      | 0.1.1                        |
|    44 | Mod Menu                                          | modmenu                                               | 5.0.2                        |
|    41 | Ok Zoomer                                         | ok_zoomer                                             | 5.0.0-beta.10+1.19.3         |
|    16 | OmegaConfig                                       | omega-config                                          | 1.2.3-1.18.1                 |
|     4 | Phosphor                                          | phosphor                                              | 0.8.1                        |
|   111 | Quilt Advancement API                             | quilt_advancement                                     | 4.0.0-beta.5+1.19.3          |
|    51 | Quilt Base API                                    | quilt_base                                            | 4.0.0-beta.5+1.19.3          |
|    67 | Quilt Biome API                                   | quilt_biome                                           | 4.0.0-beta.5+1.19.3          |
|   109 | Quilt Block Content Registry API                  | quilt_block_content_registry                          | 4.0.0-beta.5+1.19.3          |
|    45 | Quilt Block Entity API                            | quilt_block_entity                                    | 4.0.0-beta.5+1.19.3          |
|    30 | Quilt Block Extensions API                        | quilt_block_extensions                                | 4.0.0-beta.5+1.19.3          |
|    66 | Quilt Client Command API                          | quilt_client_command                                  | 4.0.0-beta.5+1.19.3          |
|    29 | Quilt Command API                                 | quilt_command                                         | 4.0.0-beta.5+1.19.3          |
|    64 | Quilt Crash Info                                  | quilt_crash_info                                      | 4.0.0-beta.5+1.19.3          |
|    38 | Quilt Dimension API                               | quilt_dimension                                       | 4.0.0-beta.5+1.19.3          |
|    52 | Quilt Entity API                                  | quilt_entity                                          | 4.0.0-beta.5+1.19.3          |
|    96 | Quilt Entity Events                               | quilt_entity_events                                   | 4.0.0-beta.5+1.19.3          |
|    40 | Quilt Entity Networking API                       | quilt_entity_networking                               | 4.0.0-beta.5+1.19.3          |
|    22 | Quilt Item Content Registry API                   | quilt_item_content_registry                           | 4.0.0-beta.5+1.19.3          |
|    56 | Quilt Item Extension API                          | quilt_item_extension                                  | 4.0.0-beta.5+1.19.3          |
|    20 | Quilt Item Setting API                            | quilt_item_setting                                    | 4.0.0-beta.5+1.19.3          |
|    98 | Quilt Lifecycle Events                            | quilt_lifecycle_events                                | 4.0.0-beta.5+1.19.3          |
|    68 | Quilt Loader                                      | quilt_loader                                          | 0.17.8                       |
|    27 | Quilt Multipart Entity API                        | quilt_entity_multipart                                | 4.0.0-beta.5+1.19.3          |
|    83 | Quilt Networking                                  | quilt_networking                                      | 4.0.0-beta.5+1.19.3          |
|    53 | Quilt Points of Interest                          | quilt_points_of_interest                              | 4.0.0-beta.5+1.19.3          |
|    88 | Quilt Recipe API                                  | quilt_recipe                                          | 4.0.0-beta.5+1.19.3          |
|    74 | Quilt Registry API                                | quilt_registry                                        | 4.0.0-beta.5+1.19.3          |
|    63 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment                       | 4.0.0-beta.5+1.19.3          |
|    79 | Quilt Resource Loader                             | quilt_resource_loader                                 | 4.0.0-beta.5+1.19.3          |
|    76 | Quilt Screen API                                  | quilt_screen                                          | 4.0.0-beta.5+1.19.3          |
|   100 | Quilt Status Effect API                           | quilt_status_effect                                   | 4.0.0-beta.5+1.19.3          |
|    92 | Quilt Surface Rule API                            | quilt_surface_rule                                    | 4.0.0-beta.5+1.19.3          |
|    78 | Quilt Tags API                                    | quilt_tags                                            | 4.0.0-beta.5+1.19.3          |
|    93 | Quilt Tooltip API                                 | quilt_tooltip                                         | 4.0.0-beta.5+1.19.3          |
|    43 | Quilt Vehicle API                                 | quilt_vehicle                                         | 4.0.0-beta.5+1.19.3          |
|    46 | Quilt Villager API                                | quilt_villager                                        | 4.0.0-beta.5+1.19.3          |
|    84 | Quilted Fabric API                                | quilted_fabric_api                                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    62 | Quilted Fabric API Base                           | quilted_fabric_api_base                               | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    70 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    59 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   101 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   110 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   108 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    37 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    39 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    36 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    48 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   105 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    50 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    28 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                   | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    65 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    85 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    49 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    91 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    61 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    31 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    54 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    23 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   112 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    97 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    69 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    90 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                            | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    21 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    60 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                         | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   107 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    58 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                              | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    32 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    26 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                      | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    47 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   106 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   102 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    94 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                       | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    71 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    24 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    34 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                 | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    77 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    80 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    42 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    73 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                    | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    35 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1             | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    99 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                     | 5.0.0-alpha.9+0.72.0-1.19.3  |
|   103 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    86 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                  | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    87 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                           | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    81 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                        | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    72 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1          | 5.0.0-alpha.9+0.72.0-1.19.3  |
|    89 | Sodium                                            | sodium                                                | 0.4.8+build.22               |
|   104 | SpruceUI                                          | spruceui                                              | 4.1.0+1.19.3                 |
|     9 | antlr4-runtime                                    | org_antlr_antlr4-runtime                              | 4.11.1                       |
|     7 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.18.5                       |
|    17 | glsl-transformer                                  | io_github_douira_glsl-transformer                     | 2.0.0-pre8                   |
|    12 | jcpp                                              | org_anarres_jcpp                                      | 1.4.14                       |
|     8 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                   | 1.8.0                        |
|     2 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                    | 1.8.0                        |
|     3 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.8.0                        |
|     5 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.8.0                        |
|    14 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                        |
|     6 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                        |
|    10 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                        |
|    19 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.4.1                        |
|    11 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.4.1                        |
|     0 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.4.1                        |
```
you can put all of that into a \<table> tag in html

**Comment by natanfudge** [comment] 2023-05-06 11:40
Duplicate of #74

**Closed by natanfudge** 2023-05-06 11:40 UTC
